### blogs
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "sara 2",
    "author": "sara 2",
    "url": "sara 2",
    "likes": 2,
}

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "sara 2",
    "author": "sara 2",
    "url": "sara 2"
}

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhcmEiLCJpZCI6IjY1MGQxN2YyMzZmOTFiZTFhYWI5N2E1ZSIsImlhdCI6MTY5NTU2NTU1NX0.uB3ZLEDcZYMFI1qLjl3YAU88NQ0f-mRwZK7lxCg7Pmo 

{
    "title": "sara 4",
    "author": "sara 4",
    "url": "sara 4",
    "likes": 5
}

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyaW4iLCJpZCI6IjY1MjA1ZWE0MDhhYmIxMTU1YTM3YTVlYiIsImlhdCI6MTY5NzE0NDIxMSwiZXhwIjoxNjk3MTQ3ODExfQ.vKJj7v9SpvsQ45nN-96IkkhE-qnWbfC50Axe1jfh1Yc

{
    "title": "sara 10",
    "author": "sara 10",
    "url": "sara 10",
    "likes": 10
}

###

GET http://localhost:3003/api/blogs/650476c18d2fe00536affaf0 HTTP/1.1

###

GET http://localhost:3003/api/blogs HTTP/1.1

###

DELETE http://localhost:3003/api/blogs/6520d743cf63c0446a965733
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyaW4iLCJpZCI6IjY1MjA1ZWE0MDhhYmIxMTU1YTM3YTVlYiIsImlhdCI6MTY5NzIxMzkxMywiZXhwIjoxNjk3MjE3NTEzfQ.AO1Pb_nswc3vKdr46EzUVsbEbgVe54OuUJpXmpa3PpA

###

### users
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "a",
    "password": "a",
    "name": "a"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "sara"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "arin",
    "name": "arin",
    "password": "arin"
}

###

GET http://localhost:3003/api/users HTTP/1.1

###

### login
GET http://localhost:3003/api/login
###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "sara",
    "password": "eric"
}
###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "sara",
    "password": "sara"
}
###

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "arin",
    "name": "arin",
    "password": "arin"
}
###

### UPDATE

PUT http://localhost:3003/api/blogs/6520d78a65160e077da7cb34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyaW4iLCJpZCI6IjY1MjA1ZWE0MDhhYmIxMTU1YTM3YTVlYiIsImlhdCI6MTY5NzIxMzkxMywiZXhwIjoxNjk3MjE3NTEzfQ.AO1Pb_nswc3vKdr46EzUVsbEbgVe54OuUJpXmpa3PpA
Content-Type: application/json

{
    "likes": 5
}