POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "sara 1",
    "author": "sara 1",
    "url": "sara 1",
    "likes": 5
}

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "author": "sara",
    "url": "sara",
    "likes": 5
}

###

GET http://localhost:3003/api/blogs/65031fb4760c4c5d337666e3 HTTP/1.1

###

DELETE http://localhost:3003/api/blogs/64fa19200630e2d4b721e291
###