# GET https://example.com/comments/1 HTTP/1.1

# ###

# GET https://example.com/topics/1 HTTP/1.1

# ###

# POST https://example.com/comments HTTP/1.1
# content-type: application/json

# {
#     "name": "sample",
#     "time": "Wed, 21 Oct 2015 18:27:50 GMT"
# }


GET http://localhost:3001/api/persons/

###

DELETE http://localhost:3001/api/persons/679

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "sara santamaria",
    "number": "777-555-4565"
}

###
GET http://localhost:3001/api/persons/64dfb292e5078918b9f00e24

###
GET http://localhost:3001/api/persons/123